import React from 'react';
import './search-bar.css';


const SearchBar = props => {
    /**
     * Prevents unintended default form behavior
     *
     * @param {event} default value generated by form
     */
    const onFormSubmit = (event) => {
         event.preventDefault();
    }

    /**
     * Executes setTermChange function sent from parent to initiate term value state update
     *
     * @param {event} default event value generated by form
     */
    const onFormChange = (event) => {
        props.onTermChange(event.target.value);
    }

    return (
        <form onSubmit={e => onFormSubmit(e)} className="ui form search">
            <div className="field">
                <label>Card Search (by name)</label>
                <input type='text' value={props.term} onChange={e => onFormChange(e)} />
            </div>
        </form>
    );
}

export default SearchBar;
